#!/bin/sh

SOLVER=$(realpath ./build/solve)
solve() {
    echo "systemd-run --user --scope -p MemoryMax=4G -p MemorySwapMax=0 $SOLVER $1 $2"
}


INPUT_DIR=$(realpath "./foo/input/")
if [ ! -d "$INPUT_DIR" ]
then
    echo "$INPUT_DIR does not exist."
    exit 1
fi

OUTPUT_DIR="./foo/output/"
mkdir -p $OUTPUT_DIR
OUTPUT_DIR=$(realpath $OUTPUT_DIR)

INSTANCE_SET_LIST=$(ls $INPUT_DIR)
for INSTACE_SET in $INSTANCE_SET_LIST
do
    echo -e "===== $INSTACE_SET ====="
    INSTACE_SET_DIR=$(realpath $INPUT_DIR/$INSTACE_SET)
    INSTANCE_LIST=$(ls $INSTACE_SET_DIR)
    for INSTANCE in $INSTANCE_LIST
    do
        echo -e "----- instance ${INSTANCE%.*} -----"
        INPUT_FILE_PATH=$(realpath $INSTACE_SET_DIR/$INSTANCE)
        OUTPUT_FILE_PATH=$OUTPUT_DIR/$INSTACE_SET/$INSTANCE
        solve $INPUT_FILE_PATH $OUTPUT_FILE_PATH
    done
done

# echo $INPUT_DIR
# echo $OUTPUT_DIR
