#!/bin/bash

list_subproject() {
    SUBPROJECT=$1
    ls \
        include/$SUBPROJECT.hpp \
        source/$SUBPROJECT.cpp\
        test/$SUBPROJECT.test.cpp
}

LOG_FILE="code_quality.log"

SRC_FILES=" \
$(list_subproject Vector3D)
$(list_subproject BoolCuboid)
$(list_subproject SmallItem)
$(list_subproject AllocatedSmallItem)
$(list_subproject LargeObject)
$(list_subproject SmallItemQuantityManager)
$(list_subproject LargestFitFirstAlgorithm)
"

echo $SRC_FILES

./script/build && \
clang-tidy \
    --quiet \
    -p "build/compile_commands.json" \
    --config-file=.clang-tidy \
    ${SRC_FILES} \
    --export-fixes=$LOG_FILE
